name: hopaut
description: HopAut - Mobile

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: "2.10.5"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_bloc:           ^6.1.3
  cupertino_icons:        ^1.0.0
  provider:               ^4.3.2+2
  visibility_detector:    0.1.5
  flutter_webview_plugin: 0.3.11
  meta: ^1.2.3
  flutter_secure_storage: 3.3.3
  fluro:                  1.7.7
  jwt_decode:             0.1.0
  fluttertoast:           4.0.1
  email_validator:        1.0.4
  flutter_translate:      1.6.0
  rxdart:                 0.24.1
  dio:                    3.0.9
  pretty_dio_logger:      ^1.1.1
  flutter_facebook_login: ^3.0.0
  mime_type:              ^0.3.2
  http_parser:            ^3.1.4
  background_fetch:       ^0.6.0
  hive:                   ^1.4.4+1
  hive_flutter:           ^0.3.1
  intl:                   ^0.16.1
  image_picker:           ^0.6.7+14
  image_cropper:          ^1.3.1
  path_provider:           ^1.6.24
  flutter_image_compress: ^0.7.0
  carousel_slider:        ^2.3.1
  flutter_typeahead:       ^1.9.1
  datetime_picker_formfield: ^1.0.0
  carousel_pro:           ^1.0.0
  material_design_icons_flutter: ^4.0.5755
  image_viewer: ^1.0.0
  timeago: ^2.0.28
  jiffy: ^3.0.1
  persistent_bottom_nav_bar: ^2.1.0
  geolocator: ^6.2.1
  onesignal_flutter: ^2.6.2
  permission_handler: ^5.0.1+1
  badges: ^1.1.4
  logger: ^0.9.4
  flutter_launcher_icons: ^0.8.1
  circular_check_box: ^1.0.4
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  animations: ^1.1.2
  table_calendar: ^2.3.1
  cached_network_image: ^2.4.1
  extended_image: ^1.3.0
  sliver_tools: ^0.1.9
  ionicons: 0.1.1
  injectable: ^1.1.2
  get_it: ^5.0.1

  flutter_cupertino_date_picker:
    git: https://github.com/yasseralsamman/flutter-cupertino-date-picker.git
  here_sdk:
    path: plugins/here_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1+1
  injectable_generator: ^1.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icons/legacy_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/facebook/
    - assets/i18n/
    - assets/icons/
    - assets/icons/launcher_icons/
    - assets/icons/map/
    - assets/icons/svg/
    - assets/fonts/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
