// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_T8Bfv8XG-VFHlr336ttrpQkBVK5FJ6U',
    appId: '1:1028951635281:android:4c8f8b0d45edc332ca0f70',
    messagingSenderId: '1028951635281',
    projectId: 'hopaut-334017',
    storageBucket: 'hopaut-334017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvGCwJGH3YcCkWStRV4OSS4Fuf1WA4jo',
    appId: '1:1028951635281:ios:028b8c917e7d7b8fca0f70',
    messagingSenderId: '1028951635281',
    projectId: 'hopaut-334017',
    storageBucket: 'hopaut-334017.appspot.com',
    androidClientId: '1028951635281-5a3nek61uu4jo6rfm7uo828s37a4abqr.apps.googleusercontent.com',
    iosClientId: '1028951635281-97qje926faipvmeb3koo46qb07d7oihe.apps.googleusercontent.com',
    iosBundleId: 'com.hopaut.hopaut',
  );
}
