enum Currency {
  eur,
  usd,
  chf,
  gbp,
  tri,
  uah,
  sek,
  ron,
  bgn,
  rub,
  rsd,
  pln,
  nok,
  mdl,
  huf,
  hrk,
  dkk,
  czk,
  cop,
  aud,
  cad,
  mxn,
  brl,
  bam,
  ars,
}

const Map<Currency, String> currencyStrings = {
  Currency.eur: 'EUR',
  Currency.usd: 'USD',
  Currency.chf: 'CHF',
  Currency.gbp: 'GBP',
  Currency.tri: 'TRY',
  Currency.uah: 'UAH',
  Currency.sek: 'SEK',
  Currency.ron: 'RON',
  Currency.bgn: 'BGN',
  Currency.rub: 'RUB',
  Currency.rsd: 'RSD',
  Currency.pln: 'PLN',
  Currency.nok: 'NOK',
  Currency.mdl: 'MDL',
  Currency.huf: 'HUF',
  Currency.hrk: 'HRK',
  Currency.dkk: 'DKK',
  Currency.czk: 'CZK',
  Currency.cop: 'COP',
  Currency.aud: 'AUD',
  Currency.cad: 'CAD',
  Currency.mxn: 'MXN',
  Currency.brl: 'BRL',
  Currency.bam: 'BAM',
  Currency.ars: 'ARS'
};
